services:
  was-1:
    build:
      context: .
    image: poc-was:latest
    container_name: poc-was-1
    environment:
      - SERVER_PORT=8080
    expose:
      - "8080"
    networks:
      - app-net

  was-2:
    image: poc-was:latest
    container_name: poc-was-2
    environment:
      - SERVER_PORT=8080
    expose:
      - "8080"
    networks:
      - app-net
    depends_on:
      - was-1

  was-3:
    image: poc-was:latest
    container_name: poc-was-3
    environment:
      - SERVER_PORT=8080
    expose:
      - "8080"
    networks:
      - app-net
    depends_on:
      - was-1

  was-4:
    image: poc-was:latest
    container_name: poc-was-4
    environment:
      - SERVER_PORT=8080
    expose:
      - "8080"
    networks:
      - app-net
    depends_on:
      - was-1

  was-5:
    image: poc-was:latest
    container_name: poc-was-5
    environment:
      - SERVER_PORT=8080
    expose:
      - "8080"
    networks:
      - app-net
    depends_on:
      - was-1

networks:
  app-net:
    external: true


